### ISSUE TITLE
Typos/Errors in R Workshop

### ISSUE THREAD

**Issue by Vholyk99** [jacobtnyoung/RWorkshop2#2]
In the You Try Section under the R Basics Page, the question what are the first through seventh elements in y says the answer is y[4:7] but it should be y[1:7]

Throughout the pages there are multiple commands using the word dat, this did not work when I tried it, but adding an a to the end to make the word data did work. 

In the Data-Driven Documents: R Markdown section, the pictures were not visible so I could not see what I was supposed to be looking for on my R software.

**Comment by jacobtnyoung** [comment]
Thanks @Vholyk99! 


For the second question, try it again and see if you are getting the error. Make sure to clear your workspace with:

```
rm(list = ls())
```
